### ISSUE TITLE
Error without Rais / Active Support

### ISSUE THREAD

**Issue by fornellas** [zedtux/cucumber-timecop#2]
Hello,

I am getting this failure:

```
    And time is frozen at now                                                                                            # cucumber-timecop-0.0.5/lib/cucumber/timecop.rb:40
      undefined method `now' for "BRT":String (NoMethodError)
      /home/fornellas/local/gems/22/gems/chronic-0.10.2/lib/chronic/parser.rb:54:in `initialize'
      /home/fornellas/local/gems/22/gems/chronic-0.10.2/lib/chronic.rb:90:in `new'
      /home/fornellas/local/gems/22/gems/chronic-0.10.2/lib/chronic.rb:90:in `parse'
      /home/fornellas/local/gems/22/gems/cucumber-timecop-0.0.5/lib/cucumber/timecop.rb:30:in `parse_time'
      /home/fornellas/local/gems/22/gems/cucumber-timecop-0.0.5/lib/cucumber/timecop.rb:24:in `freeze_time_at'
      /home/fornellas/local/gems/22/gems/cucumber-timecop-0.0.5/lib/cucumber/timecop.rb:41:in `block in <top (required)>'
```

It seems like, here is the cause:
https://github.com/zedtux/cucumber-timecop/blob/master/lib/cucumber/timecop.rb#L50
It sets Chronic.time_class to Time.now.zone in my case (no Rails). It tries to do something like:
https://github.com/mojombo/chronic/blob/master/lib/chronic.rb#L47
but it does not work:

```
irb(main):002:0> Chronic.time_class
=> Time
irb(main):003:0> Chronic.parse 'now'
=> 2015-10-13 12:33:55 -0300
irb(main):004:0> Chronic.time_class = Time.now.zone
=> "BRT"
irb(main):005:0> Chronic.parse 'now'
NoMethodError: undefined method `now' for "BRT":String
	from /home/fornellas/local/gems/22/gems/chronic-0.10.2/lib/chronic/parser.rb:54:in `initialize'
	from /home/fornellas/local/gems/22/gems/chronic-0.10.2/lib/chronic.rb:90:in `new'
	from /home/fornellas/local/gems/22/gems/chronic-0.10.2/lib/chronic.rb:90:in `parse'
	from (irb):5
	from /opt/ruby22/bin/irb:11:in `<main>'
```

I guess the appropriate fix, for no Rails would be to maintain Chronic's original value:
https://github.com/mojombo/chronic/blob/master/lib/chronic.rb#L80
with:
`Chronic.time_class = defined?(Rails) ? Time.zone : ::Time`

**Comment by zedtux** [comment]
Why do you think the issue come from my gem ? In my opinion, it's a Chronic issue.

**Comment by fornellas** [comment]
Because originally, #time_class is a Time class reference:
https://github.com/mojombo/chronic/blob/master/lib/chronic.rb#L80
irb(main):003:0> Time.class
=> Class
With your library, #time_class is set to a String:
https://github.com/zedtux/cucumber-timecop/blob/master/lib/cucumber/timecop.rb#L50
irb(main):004:0> Time.now.zone.class
=> String
Thus, generating the error:
      undefined method `now' for "BRT":String (NoMethodError)
("BRT" is my Time.now.zone).

**Comment by zedtux** [comment]
Thank you for the information, I better understand now.
